### ISSUE TITLE
React Peer Dependency

### ISSUE THREAD

**Issue by jspizziri** [ignatevdev/final-form-submit-errors#7]
It appears that this packages [uses the `@types/react` for `v17`](https://github.com/ignatevdev/final-form-submit-errors/blob/master/package.json#L41)  however has [a `peerDependency` of `react@~16`](https://github.com/ignatevdev/final-form-submit-errors/blob/master/package.json#L71)

Is it possible to bump the `peerDependency` to `17`? Or is there more work to refactor the package to function properly with that version?

Thanks!

**Comment by ignatevdev** [comment]
@jspizziri, Hi!

Yes, I've updated the react's peerDependency version in package.json and rolled out version 0.1.4.

Can you check if everything's good now?

**Comment by jspizziri** [comment]
@ignatevdev I can confirm the install issue I was facing is resolved. Thanks!
